#!/bin/bash
# Fix Duplicate LinkedIn Recruiter Cron Job
# Generated by cron verification - 2026-03-02

echo "🔧 Fixing duplicate LinkedIn recruiter cron job..."

# Backup current crontab
crontab -l > ~/clawd/crontab-backup-$(date +%Y%m%d-%H%M%S).txt
echo "✅ Backed up current crontab"

# Remove the duplicate entry (line 54)
crontab -l | grep -v "^0 9 \* \* \* cd ~/job-hunter-system && python3 follow_it_recruiters.py >> ~/clawd/logs/linkedin-auto.log" | crontab -

echo "✅ Removed duplicate LinkedIn recruiter job at 9 AM"
echo "✅ Kept aggressive mode schedule (every 3 hours)"

# Verify
echo ""
echo "Current LinkedIn recruiter entries:"
crontab -l | grep -A1 "LinkedIn recruiter"

echo ""
echo "✅ Fix applied successfully!"
echo "📝 Backup saved to ~/clawd/crontab-backup-*.txt"
